# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=200, verbose_name='Hostname')),
                ('machine_address', models.CharField(max_length=200, verbose_name='Adress')),
                ('machine_port', models.IntegerField(verbose_name='Port')),
                ('machine_http_username', models.CharField(max_length=200, verbose_name='Username')),
                ('machine_http_password', models.CharField(max_length=200, verbose_name='Password')),
            ],
            options={
                'ordering': ['machine_name', 'machine_address'],
            },
        ),
    ]
