# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_http_password',
            field=models.CharField(default=None, max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_http_username',
            field=models.CharField(default=None, max_length=200, verbose_name='Username'),
        ),
    ]
