# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160331_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_http_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_http_username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Username'),
        ),
    ]
